name:                anek
version:             0.1.0.0
github:              "spkirich/anek"
license:             BSD3
author:              "Sergey Kirichenko"
maintainer:          "s2002kir@yandex.ru"
copyright:           "2022 Sergey Kirichenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/spkirich/anek#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- http-conduit
- random
- tagsoup

library:
  source-dirs: src

executables:
  anek-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - anek

tests:
  anek-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - anek
